<?php
/**
 */

namespace execut\navigation\page;


use execut\navigation\TestCase;
use yii\i18n\I18N;

class HomeTest extends TestCase
{
    public function setUp(): void
    {
        $this->mockWebApplication([
            'components' => [
                'i18n' => [
                    'class' => I18N::class,
                    'translations' => [
                        '*' => [
                            'class' => 'yii\i18n\PhpMessageSource',
                            'sourceLanguage' => 'en-US',
                            'basePath' => '@yii/messages',
                        ],
                    ],
                ],
            ],
        ]);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown(): void
    {
        $this->destroyApplication();
        parent::tearDown();
    }

    public function testSetName() {
        $homePage = new Home();
        $this->assertEquals('Home', $homePage->getTitle());
        $this->assertEquals('/', $homePage->getUrl());
    }
}